-- 删除旧的不兼容的表
DROP TABLE IF EXISTS reports CASCADE;
DROP TABLE IF EXISTS test_templates CASCADE;
DROP TABLE IF EXISTS calibration_settings CASCADE;
DROP TABLE IF EXISTS defects CASCADE;
DROP TABLE IF EXISTS waveform_data CASCADE;
DROP TABLE IF EXISTS test_records CASCADE;

